### ISSUE TITLE
Python style enforcement

### ISSUE THREAD

**Issue by GreyCat** [kaitai-io/kaitai_struct_python_runtime#26]
Python runtime might use some Python style enforcement. I actually don't know a thing about Python coding, so I'm asking for help from knowledgeable folks out there — cc @KOLANICH @koczkatamas @arekbulski @dgladkov.

I see that there is [PEP8](https://www.python.org/dev/peps/pep-0008/), [PEP257](https://www.python.org/dev/peps/pep-0257/), [Google style guide](https://google.github.io/styleguide/pyguide.html), and a handful of less widespread style guides. There are tons of tools that offer some kind of enforcement:

* [pylint](https://github.com/PyCQA/pylint)
* [pep8](https://pypi.python.org/pypi/pep8), which is said to be evolved into [pycodestyle](https://pypi.python.org/pypi/pycodestyle)
* [pyflakes](https://pypi.python.org/pypi/pyflakes)
* [flake8](https://pypi.python.org/pypi/flake8)
* [prospector](https://prospector.landscape.io/en/)
* [pyroma](https://pypi.python.org/pypi/pyroma/)
* etc

Currently, we have [codacy.com](https://app.codacy.com/app/greycat-na-kor/kaitai_struct_python_runtime/dashboard) checking our Python runtime with Bandit, Prospector & PyLint, but their configuration is mostly defaults which were been chosen by Codacy team.

Which coding style / tool should we choose? Let's decide on this and add some sort of config for it into this repository?

**Comment by KOLANICH** [comment]
I personally prefer "my" coding style:
1 tabs, a tab is 4 character long
2 lf line ends
3 camelCase for variables
4 CamelCase for classes and enums
5 camelCase for members of enums, no prefix in value name
6 no line length limit, but
6 quite arbitrary but meaningful grouping and alignment:
 * long functions, expressions and generators are to be splitted into multiple lines by operators and are indented with one tab for one level of nesting:
```python
def a(
  arg 1,
  arg 2
):
```
```python
if(
  a and b
  or
  c and d
)
```
* similar expressions can be aligned with tabs
```python
a[ 0] =  1
a[10] = 10
```
* a brackets stick together and separated from content with indentation reflecting nesting level
```python
", ".join((  str(i) for i in ( i**3 for i in range(10) )  ))
```

**Comment by flucknugget** [comment]
Another option is [Black](https://github.com/ambv/black):

> Black is the uncompromising Python code formatter. By using it, you agree to cede control over minutiae of hand-formatting. In return, Black gives you speed, determinism, and freedom from pycodestyle nagging about formatting. You will save time and mental energy for more important matters.
>
> Blackened code looks the same regardless of the project you're reading. Formatting becomes transparent after a while and you can focus on the content instead.
>
> Black makes code review faster by producing the smallest diffs possible.

- editor integration is great: https://github.com/ambv/black#editor-integration
- a pre-commit hook is provided: https://github.com/ambv/black#version-control-integration
- there is also an argument `--check` for verifying that a file follows Black codestyle (for CI)

**Comment by generalmimon** [comment]
Can this issue be closed now that @GreyCat has already implemented code style checking with https://github.com/andymckay/pycodestyle-action GH Action (https://github.com/kaitai-io/kaitai_struct_python_runtime/commit/4a3562bccd0a8d3a48cbbc5a87ea20c6bf931bfc)?

**Comment by KOLANICH** [comment]
If so, yes. `pylint` and maybe even `mypy` also should be handy.
