### ISSUE TITLE
Unable to install 0.9 with Pipenv

### ISSUE THREAD

**Issue by tvbui** [kaitai-io/kaitai_struct_python_runtime#55]
Using pipenv --version
pipenv, version 2020.11.15

pipenv run python -version
Python 3.6.3

When I try to run the following command to install kaitaistruct version 0.9, I get the following error.

$**pipenv run python -m pip install kaitaistruct==0.9**
Collecting pip
  Using cached https://nexus.fanops.net/nexus/repository/pypi-all/packages/pip/20.3.1/pip-20.3.1-py2.py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 9.0.1
    Uninstalling pip-9.0.1:
      Successfully uninstalled pip-9.0.1
Successfully installed pip-20.3.1
Looking in indexes: http://pypi/nexus/repository/pypi-all/simple
Collecting kaitaistruct
  Using cached https://nexus.fanops.net/nexus/repository/pypi-all/packages/kaitaistruct/0.9/kaitaistruct-0.9.tar.gz (5.5 kB)
  WARNING: Generating metadata for package kaitaistruct produced metadata for project name unknown. Fix your #egg=kaitaistruct fragments.
ERROR: Requested unknown from https://nexus.fanops.net/nexus/repository/pypi-all/packages/kaitaistruct/0.9/kaitaistruct-0.9.tar.gz#sha256=3d5845817ec8a4d5504379cc11bd570b038850ee49c4580bc0998c8fb1d327ad has different name in metadata: 'UNKNOWN'

When I try to run the following command to install kaitaistruct version 0.8, I get no errors.
$**pipenv run python -m pip install kaitaistruct==0.8**
Collecting pip
  Using cached https://nexus.fanops.net/nexus/repository/pypi-all/packages/pip/20.3.1/pip-20.3.1-py2.py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 9.0.1
    Uninstalling pip-9.0.1:
      Successfully uninstalled pip-9.0.1
Successfully installed pip-20.3.1
Looking in indexes: http://pypi/nexus/repository/pypi-all/simple
Collecting kaitaistruct==0.8
  Downloading https://nexus.fanops.net/nexus/repository/pypi-all/packages/kaitaistruct/0.8/kaitaistruct-0.8.tar.gz (5.2 kB)
Building wheels for collected packages: kaitaistruct
  Building wheel for kaitaistruct (setup.py): started
  Building wheel for kaitaistruct (setup.py): finished with status 'done'
  Created wheel for kaitaistruct: filename=kaitaistruct-0.8-py2.py3-none-any.whl size=7059 sha256=44206a142e396c5afe17da3b3e7f1873e8b803f38c8aabe95f28b01e20d148d1
  Stored in directory: /var/lib/jenkins/.cache/pip/wheels/71/b6/db/5f356e240aeacbe63f3e4cd874a16f15b4ee21f6ec05c317d3
Successfully built kaitaistruct
Installing collected packages: kaitaistruct
Successfully installed kaitaistruct-0.8

Could somebody help me know I can do to resolve?

**Comment by dgelessus** [comment]
> Found existing installation: pip 9.0.1

It seems that you have a very old version of pip installed (pip 9.0.1 is from November 2016). If your installed version of setuptools is also this old, you won't be able to install the Kaitai Struct runtime, because it requires a relatively new setuptools version.

Can you run `python -m pip install --upgrade pip`, then `python -m pip install --upgrade setuptools wheel`, and then try again if `python -m pip install kaitaistruct` works?

**Comment by tvbui** [comment]
Hi @dgelessus , updating setuptools and wheel did the trick. Thanks again for your help and prompt response!
