### ISSUE TITLE
Missing Runtime Dependency on `pkg_resources`

### ISSUE THREAD

**Issue by mhils** [kaitai-io/kaitai_struct_python_runtime#62]
Kaitai's generated Python parsers currently depend on `pkg_resources`, which is not specified as a dependency of `kaitaistruct`. This problem isn't very visible as most environments still have setuptools around (which includes `pkg_resources`), but if setuptools is not around in the current virtualenv, importing parsers crashes with an `ImportError`.

One could argue that Kaitai's behavior is technically correct: The actual import is done in the downstream codebase -- in the Python file generated by `ksc` -- and not within the `kaitaistruct` package. However, all generated Kaitai parsers have this dependency, and it seems relatively stupid and brittle to have every single Kaitai user add an additional dependency for `pkg_resources` themselves. Long story short, I think `kaitaistruct` should have packages that are required by all ksc-generated parsers to its own dependency list.

With this aside, @asottile (who initially reported this to us in @mitmproxy) made the very helpful suggestion in https://github.com/mitmproxy/mitmproxy/issues/4918#issuecomment-974456344 that the generated parser should ideally just use `importlib.metadata` from stdlib instead of dependening on `pkg_resources`. Unfortunately `importlib.metadata` has only been added in Python 3.8, so just changing `ksc` is not enough. Long story short, I propose the following changes:

1. Make the `kaitaistruct` PyPI package depend on the [`importlib-metadata`](https://pypi.org/project/importlib-metadata/) PyPI package for Python <3.8 (see https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#platform-specific-dependencies). 
This means no new (de facto less) dependencies for anyone on a recent Python version.
2. Once a new `kaitaistruct` version is released on PyPI that includes these changes, update `ksc` to emit parsers that use `importlib.metadata`  instead of `pkg_resources`.

**Comment by KOLANICH** [comment]
I think the generated parsers should not depend on pkg_resources. It is imported there for just a version comparison routine. IMHO it doesn't bring a large benefit. I guess just a variable starting with underscore describing the version (just a tuple) of the transpiker and a comment that the same version of runtime is needed is enough. If nothing is broken - then OK. If something is broken - the one who gonna investigate would notice. For the ones wanting an automatic check, a routine within the runtime can be implemented that would just take module object, use the variable and raise an exception if it is incompatible.

**Comment by mhils** [comment]
@asottile: Potentially stupid follow-up question: `importlib.metadata` does not provide an equivalent of `pkg_resources`'s `parse_version`, does it? Because that's all that is used from `pkg_resources`, so `importlib.metadata` would not help that much.

Just comparing a tuple (as @KOLANICH suggested) might be the easier approach forward here then.

**Comment by generalmimon** [comment]
@mhils:

> Kaitai's generated Python parsers currently depend on `pkg_resources`, which is not specified as a dependency of `kaitaistruct`.

AFAIR, @dgelessus discovered in https://github.com/kaitai-io/kaitai_struct/issues/804 that `import pkg_resources` is slow and we're only using it for parsing the version to verify that the runtime library version is compatible with the generated module, so I guess we'll be eliminating `pkg_resources` as a dependency anyway. The version parsing will probably be replaced with storing the version directly in a tuple like `(0, 9)` and then simply comparing two tuples in the generated parser.

Once this is done, this issue becomes pointless.

**Comment by mhils** [comment]
I didn't see #804, apologies! I'll close my PR then, using a tuple is the better approach here.

**Comment by asottile** [comment]
> @asottile: Potentially stupid follow-up question: `importlib.metadata` does not provide an equivalent of `pkg_resources`'s `parse_version`, does it? Because that's all that is used from `pkg_resources`, so `importlib.metadata` would not help that much.
> 
> Just comparing a tuple (as @KOLANICH suggested) might be the easier approach forward here then.

not a stupid question!  an oversight on my part -- comparing a splitted, parsed tuple is all that's needed (I assumed this was using `importlib.metadata.version(...)` to query the installed `kataistruct`)

**Comment by generalmimon** [comment]
Solved by adopting https://github.com/kaitai-io/kaitai_struct/issues/804
