### ISSUE TITLE
Delete or fix MANIFEST.in (only references non-existent README.rst)

### ISSUE THREAD

**Issue by generalmimon** [kaitai-io/kaitai_struct_python_runtime#65]
I don't know what purpose this file has/had, but it references a non-existent file README.rst, which can't be right:

https://github.com/kaitai-io/kaitai_struct_python_runtime/blob/cb8f43106bc21384aa570a36fe911dd3f1056e58/MANIFEST.in#L1

**Comment by KOLANICH** [comment]
Also take a look at #65. `setuptools` has implemented PEP 621, so I have migrated everything to `pyproject.toml`. Unfortunately there is a bug in `setuptools`, reading a variable from `py-modules` doesn't work, it tries to open `__init__.py` which doesn't exist.

**Comment by generalmimon** [comment]
Actually `README.rst` is still referenced by `setup.cfg`:

https://github.com/kaitai-io/kaitai_struct_python_runtime/blob/cb8f43106bc21384aa570a36fe911dd3f1056e58/setup.cfg#L8

Should this reference be updated to `README.md`?

**Comment by KOLANICH** [comment]
Fixed. Also I have hardcoded the version into `pyproject.toml` as a workaround.
