### ISSUE TITLE
PyPI project page does not link to GitHub repo

### ISSUE THREAD

**Issue by generalmimon** [kaitai-io/kaitai_struct_python_runtime#69]
I've just noticed that https://pypi.org/project/kaitaistruct/ doesn't contain any backlink to the source repository, i.e. https://github.com/kaitai-io/kaitai_struct_python_runtime. The "Homepage" in Project links leads to https://kaitai.io:

![image](https://user-images.githubusercontent.com/47499687/178085954-11e0c021-795b-437e-a1f3-4eb7cde93dd6.png)

..., which I guess is fine because it's indeed the homepage of the _project_, but the repo with source code of the package at PyPI is not directly reachable.

I wonder how it can be expressed in `setup.cfg` - it looks like [`project_urls`](https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#project-urls) is intended for that purpose?

> List additional relevant URLs about your project. This is the place to link to bug trackers, source repositories, or where to support package development. The string of the key is the exact text that will be displayed on PyPI.

`project_urls` needs [`setuptools >= 38.3.0`](https://setuptools.pypa.io/en/latest/userguide/declarative_config.html#metadata), which is fine, because we already require an even later version (because of the `long_description_content_type` we're using):

https://github.com/kaitai-io/kaitai_struct_python_runtime/blob/c29609940a4cee756c35b5d6d429ba00aa4ec99f/setup.cfg#L37-L38

**Comment by dgelessus** [comment]
Yes, `project_urls` is the correct thing to use here. See for example:

https://github.com/beeware/rubicon-objc/blob/d4533001eee0c7349ebf0007993e9489ba948fc6/setup.cfg#L5-L9
