### ISSUE TITLE
read->write->read raises UnsupportedOperation: read error on a file but not on a BytesIO

### ISSUE THREAD

**Issue by fragmede** [kaitai-io/kaitai_struct_python_runtime#79]
Hi,

I read, write, and then read a file, but it throws an error.

```python
from kaitaistruct import KaitaiStream
from png import Png
data = Png.from_file('1x1.png')
data._read()
buffer = open('out.png', 'wb')
buffer.truncate(data._io.size())
_io = KaitaiStream(buffer)
data._write(_io)
_io.seek(0)
data._read()
```

throws

```python
File ~/projects/speedier/jupyter_env/lib/python3.10/site-packages/kaitaistruct.py:392, in KaitaiStream._read_bytes_not_aligned(self, n)
    389     is_satisfiable = (n <= num_bytes_available)
    391 if is_satisfiable:
--> 392     r = self._io.read(n)
    393     num_bytes_available = len(r)
    394     is_satisfiable = (n <= num_bytes_available)

UnsupportedOperation: read
```

If I use an bytesio buffer instead:

```python
from kaitaistruct import KaitaiStream
import io
from png import Png
data = Png.from_file('1x1.png')
data._read()
buffer = io.BytesIO(bytearray(data._io.size()))
_io = KaitaiStream(buffer)
data._write(_io)
_io.seek(0)
data._read()
```

No error is thrown.

I am running with kaitai_struct_python_runtime at `92a2d71519ba`.

**Comment by generalmimon** [comment]
> I read, write, and then read a file, but it throws an error.

The problem is that you opened the file in write-only mode, but later try to read from it:

```python
# ...
buffer = open('out.png', 'bw')  # mode='wb' => open for writing only!  ---+
buffer.truncate(data._io.size())  #                                       |
_io = KaitaiStream(buffer)  #                                             |
data._write(_io)  #                                                       |
_io.seek(0)  #                                                            |
data._read()  #  <--------------------------------------------------------+
              #  attempt to read from a write-only file => Python throws "UnsupportedOperation: read"
```

Check https://docs.python.org/3/library/functions.html#open for a list of `open()` modes:

Character | Meaning
-- | --
`'w'` | open for <ins>**writing**</ins>, truncating the file first

To open a file in read-write mode, you can choose any mode with `+` instead. `r+`, `w+` or `x+` should all work (see also https://stackoverflow.com/a/67558256/12940655 for how they differ). Please just don't use `a+`, otherwise seeking won't work :)

> If I use an bytesio buffer instead:

Yes, because `io.BytesIO` is allows both reading and writing. Simple as that.

**Comment by fragmede** [comment]
Ah doh, thanks.

**Comment by generalmimon** [comment]
Also, as a side note: you should use the `with` keyword to manage the `KaitaiStream`, see https://doc.kaitai.io/serialization.html#_bit_sized_integers:

> If you use a [file object](https://docs.python.org/3/glossary.html#term-file-object) (typically from [**open()**](https://docs.python.org/3/library/functions.html#open)) to initialize the `KaitaiStream`, it’s best to use the with keyword to manage the stream. But given that `KaitaiStream` relies on being fixed-length, note that the file must already have the final size once you pass it to `KaitaiStream` (the `KaitaiStream` object currently remembers the stream size at creation time and won’t allow `write*()` methods to exceed it). You can use [**truncate()**](https://docs.python.org/3/library/io.html#io.IOBase.truncate) to set the file length. Like this:
> 
> ```python
> f = open('path/to/file.bin', 'wb')  # use io.open() instead if you care about Python 2 compatibility
> f.truncate(8)
> 
> with KaitaiStream(f) as _io:
>     hw._write(_io)
> ```
> 
> Note that it’s not necessary to manage the file object using the `with` keyword too - `KaitaiStream` consumes the given underlying I/O stream (in this case the file object `f`) and takes care of closing it once it’s being closed itself.
